# Generated by Django 5.2.12 on 2026-03-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislature', '0004_alter_billaction_status_textfield'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='billaction',
            index=models.Index(fields=['session', 'bill_number'], name='legislature_session_520c70_idx'),
        ),
        migrations.AddIndex(
            model_name='billtext',
            index=models.Index(fields=['session', 'bill_number'], name='legislature_session_bc04eb_idx'),
        ),
        migrations.AddIndex(
            model_name='legislator',
            index=models.Index(fields=['session', 'chamber'], name='legislature_session_a4c020_idx'),
        ),
        migrations.AddIndex(
            model_name='legislator',
            index=models.Index(fields=['session', 'party'], name='legislature_session_ad53e4_idx'),
        ),
        migrations.AddIndex(
            model_name='rollcall',
            index=models.Index(fields=['session', 'chamber'], name='legislature_session_259081_idx'),
        ),
        migrations.AddIndex(
            model_name='rollcall',
            index=models.Index(fields=['session', 'bill_number'], name='legislature_session_a0e04f_idx'),
        ),
        migrations.AddIndex(
            model_name='rollcall',
            index=models.Index(fields=['vote_date'], name='legislature_vote_da_aecbdc_idx'),
        ),
    ]
